<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SephiriaToolbox</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SephiriaManaged Condition="'$(SephiriaManaged)' == '' And $([MSBuild]::IsOSPlatform('OSX'))">$(HOME)/Library/Application Support/Steam/steamapps/common/Sephiria/Sephiria.app/Contents/Resources/Data/Managed</SephiriaManaged>
    <SephiriaManaged Condition="'$(SephiriaManaged)' == '' And $([MSBuild]::IsOSPlatform('Windows'))">C:\Program Files (x86)\Steam\steamapps\common\Sephiria\Sephiria_Data\Managed</SephiriaManaged>
    <SephiriaManaged Condition="'$(SephiriaManaged)' == ''">$(HOME)/.steam/steam/steamapps/common/Sephiria/Sephiria_Data/Managed</SephiriaManaged>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(SephiriaManaged)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mirror"><HintPath>$(SephiriaManaged)/Mirror.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(SephiriaManaged)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(SephiriaManaged)/UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(SephiriaManaged)/UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.InputSystem"><HintPath>$(SephiriaManaged)/Unity.InputSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(SephiriaManaged)/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(SephiriaManaged)/Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Lang\*.json" LogicalName="Lang.%(Filename).json" />
  </ItemGroup>
</Project>
